/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo1p;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JInternalFrame;

/**
 *
 * @author ranbr
 */
public class Principal extends javax.swing.JFrame {

    private MantenimientoProducto ventanaProducto;
   

    public static String BD = "jdbc:mysql://localhost/multibodegas";
    public static String Usuario = "root";
    public static String Contraseña = "Polo.2015";

    /**
     * Creates new form MDI
     */
    
     public void CentrarVentanas(JInternalFrame internalFrame){
        
        int x = (ventanaP.getWidth( ) / 2)- internalFrame.getWidth() / 2;
        int y = (ventanaP.getHeight() / 2)- internalFrame.getHeight() / 2;
        
       if (internalFrame.isShowing () ){
           internalFrame.setLocation (x,  y);
       }
    
    else {
    ventanaP.add(internalFrame);
    internalFrame.setLocation(x,  y);
    internalFrame.show();
}
    }
    public Principal() {
        initComponents();
    }

    public static Connection getConeccion() {
        Connection cn = null;
        try {
            Class.forName(BD);
            cn = DriverManager.getConnection(Principal.BD, Principal.Usuario, Principal.Contraseña);

        } catch (Exception e) {
            System.out.println(String.valueOf(e));
        }
        return cn;

    }
    public static ResultSet getTablaUsuarios(String Consulta){
        Connection cn = getConeccion();
        Statement st = null ;
        ResultSet datos=null;
       
        try{
            datos=st.executeQuery((Consulta));
        }catch(Exception e){ System.out.print(e.toString());}
        return datos;
    
    }
    public void Panel(){
    ventanaP.removeAll();
       ventanaP.repaint();
       ventanaP.revalidate();
        
       ventanaP.repaint();
        ventanaP.revalidate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        ventanaP = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MAlumnos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rachel Barrios 9959-18-649");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f1.jpg"))); // NOI18N

        ventanaP.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ventanaPLayout = new javax.swing.GroupLayout(ventanaP);
        ventanaP.setLayout(ventanaPLayout);
        ventanaPLayout.setHorizontalGroup(
            ventanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ventanaPLayout.setVerticalGroup(
            ventanaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));

        jMenu5.setText("Abrir");
        jMenuBar1.add(jMenu5);

        jMenu1.setText("Catalogo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MAlumnos.setText("Mantenimiento Producto");
        MAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(MAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Procesos");
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Informes");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Herramientas");
        jMenuBar1.add(jMenu7);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaP)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAlumnosActionPerformed
        ventanaProducto = new MantenimientoProducto();
        Panel();
        CentrarVentanas(ventanaProducto);
        ventanaP.add(jLabel1);
        // TODO add your handling code here:
    }//GEN-LAST:event_MAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane ventanaP;
    // End of variables declaration//GEN-END:variables
}
